# Generated by Django 2.0.5 on 2018-05-15 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_client_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(default='Nowy', max_length=10, verbose_name='Nick'),
        ),
    ]
