# Generated by Django 2.0.5 on 2018-05-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180515_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.URLField(default='http://www.winhelponline.com/blog/wp-content/uploads/2017/12/user.png', verbose_name='Avatar'),
        ),
    ]
