# Generated by Django 2.0.5 on 2018-05-15 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_client_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nickname',
            field=models.CharField(default='Nowy', max_length=20, verbose_name='Nick'),
        ),
    ]
