# Generated by Django 2.0.5 on 2018-05-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Imię')),
                ('sur_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('tel', models.CharField(max_length=9, verbose_name='Telefon')),
                ('pesel', models.CharField(max_length=11, verbose_name='Pesel')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
    ]
