# Generated by Django 2.0.5 on 2018-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hire', '0004_auto_20180511_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire',
            name='comments',
            field=models.TextField(verbose_name='Uwagi'),
        ),
    ]
