# Generated by Django 2.0.5 on 2018-05-22 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('action', models.CharField(max_length=30, verbose_name='Akcja:')),
                ('addition', models.CharField(default='', max_length=30, verbose_name='Dodatkowe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logi',
                'verbose_name_plural': 'Logi',
            },
        ),
    ]
