# Generated by Django 2.0.5 on 2018-05-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logi',
            name='car',
            field=models.IntegerField(default=1, verbose_name='ID auta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logi',
            name='raport',
            field=models.IntegerField(default=2, verbose_name='ID raportu'),
            preserve_default=False,
        ),
    ]
