# Generated by Django 2.0.5 on 2018-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logi', '0004_auto_20180525_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logi',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
