# Generated by Django 2.0.5 on 2018-05-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('mark', models.CharField(max_length=20, verbose_name='Marka')),
                ('gearbox', models.CharField(max_length=20, verbose_name='Skrzynia biegów')),
                ('fuel', models.CharField(max_length=20, verbose_name='Paliwo')),
                ('type', models.CharField(max_length=20, verbose_name='Typ')),
                ('charge', models.CharField(max_length=20, verbose_name='Koszt')),
                ('photo', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Car_with_Driver-Silhouette.svg/916px-Car_with_Driver-Silhouette.svg.png', verbose_name='Zdjęcie')),
                ('checked', models.BooleanField(default=False, verbose_name='Wypożyczony')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
    ]
