# Generated by Django 2.0.5 on 2018-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20180511_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('tt', 'Hatchback'), ('ss', 'Sedan'), ('dd', 'Kombi')], max_length=20),
        ),
    ]
