# Generated by Django 2.0.5 on 2018-05-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20180514_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('hh', 'Hatchback'), ('se', 'Sedan'), ('ko', 'Kombi'), ('sc', 'Sportowe | Coupe'), ('kb', 'Kabriolet'), ('li', 'Limuzyna'), ('pi', 'Pickup'), ('te', 'Terenowe'), ('vm', 'Van | Minibus')], max_length=20),
        ),
    ]
