# Generated by Django 2.0.5 on 2018-05-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20180514_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('ON', 'Diesel'), ('PB', 'Benzyna'), ('PBLPG', 'Benzyna + LPG')], max_length=20, verbose_name='Paliwo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('mm', 'Manualna'), ('aa', 'Automatyczna'), ('ma', 'Pół Automatyczna')], max_length=20, verbose_name='Skrzynia biegów'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('hh', 'Hatchback'), ('se', 'Sedan'), ('ko', 'Kombi'), ('sc', 'Sportowe | Coupe'), ('kb', 'Kabriolet'), ('li', 'Limuzyna'), ('pi', 'Pickup'), ('te', 'Terenowe'), ('vm', 'Van | Minibus')], max_length=20, verbose_name='Typ'),
        ),
    ]
