# Generated by Django 2.0.5 on 2018-05-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20180514_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(default='Brak', max_length=60, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(max_length=20, verbose_name='Paliwo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.CharField(max_length=20, verbose_name='Skrzynia biegów'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(max_length=20, verbose_name='Typ'),
        ),
    ]
