# Generated by Django 2.0.5 on 2018-05-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20)),
                ('marka', models.CharField(max_length=20)),
                ('skrzynia', models.CharField(max_length=20)),
                ('paliwo', models.CharField(max_length=20)),
                ('typ', models.CharField(max_length=20)),
                ('koszt', models.IntegerField()),
                ('wypozyczony', models.BooleanField(default=False)),
            ],
        ),
    ]
