# Generated by Django 2.0.5 on 2018-05-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('mark', models.CharField(max_length=20, verbose_name='Marka')),
                ('gearbox', models.CharField(max_length=20, verbose_name='Skrzynia biegów')),
                ('fuel', models.CharField(max_length=20, verbose_name='Paliwo')),
                ('type', models.CharField(max_length=20, verbose_name='Typ')),
                ('charge', models.CharField(max_length=20, verbose_name='Koszt')),
                ('photo', models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Car_with_Driver-Silhouette.svg/916px-Car_with_Driver-Silhouette.svg.png', verbose_name='Zdjęcie')),
                ('checked', models.BooleanField(default=False, verbose_name='Wypożyczony')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Tytuł')),
                ('Comments', models.CharField(max_length=30, verbose_name='Uwagi')),
                ('data', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Car')),
            ],
            options={
                'verbose_name': 'Wypożyczenie',
                'verbose_name_plural': 'Wypożyczenia',
            },
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Imię')),
                ('sur_name', models.CharField(max_length=50, verbose_name='Nazwisko')),
                ('tel', models.CharField(max_length=9, verbose_name='Telefon')),
                ('pesel', models.CharField(max_length=11, verbose_name='Pesel')),
            ],
            options={
                'verbose_name': 'Klient',
                'verbose_name_plural': 'Klienci',
            },
        ),
        migrations.AddField(
            model_name='hire',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Lender'),
        ),
    ]
