# Generated by Django 2.0.5 on 2018-05-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='pesel',
            field=models.CharField(max_length=11, verbose_name='Pesel'),
        ),
    ]
