# Generated by Django 2.0.5 on 2018-05-09 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='wypozyczony',
        ),
    ]
