# Generated by Django 2.0.5 on 2018-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_auto_20180510_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
