# Generated by Django 2.0.5 on 2018-05-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked', models.BooleanField(default=False)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Auto')),
            ],
        ),
        migrations.CreateModel(
            name='Lender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pesel', models.IntegerField(max_length=11)),
                ('name', models.CharField(max_length=20)),
                ('sur_name', models.CharField(max_length=50)),
                ('tel', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='hire',
            name='lender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auto.Lender'),
        ),
    ]
