# Generated by Django 2.0.5 on 2018-05-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0003_auto_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='checked',
            field=models.BooleanField(default=False, verbose_name='Wypożyczony'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='photo',
            field=models.URLField(default='https://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Car_with_Driver-Silhouette.svg/916px-Car_with_Driver-Silhouette.svg.png', verbose_name='Zdjęcie'),
        ),
    ]
