# Generated by Django 2.0.5 on 2018-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_auto_20180509_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lender',
            name='pesel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lender',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
