# Generated by Django 2.0.5 on 2018-05-09 13:36

import auto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0005_auto_20180509_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='koszt',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='hire',
            name='checked',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hire',
            name='lender',
            field=models.CharField(max_length=30, verbose_name=auto.models.Lender),
        ),
        migrations.AlterField(
            model_name='lender',
            name='pesel',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='lender',
            name='tel',
            field=models.CharField(max_length=9),
        ),
    ]
