# Generated by Django 2.0.2 on 2018-05-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=20, verbose_name='Model')),
                ('mark', models.CharField(max_length=20, verbose_name='Marka')),
                ('gearbox', models.CharField(choices=[('mm', 'Manualna'), ('aa', 'Automatyczna'), ('ma', 'Pół Automatyczna')], max_length=20, verbose_name='Skrzynia biegów')),
                ('fuel', models.CharField(choices=[('ON', 'Diesel'), ('PB', 'Benzyna'), ('PBLPG', 'Benzyna + LPG')], max_length=20, verbose_name='Paliwo')),
                ('type', models.CharField(choices=[('hh', 'Hatchback'), ('se', 'Sedan'), ('ko', 'Kombi'), ('sc', 'Sportowe | Coupe'), ('kb', 'Kabriolet'), ('li', 'Limuzyna'), ('pi', 'Pickup'), ('te', 'Terenowe'), ('vm', 'Van | Minibus')], max_length=20, verbose_name='Typ')),
                ('description', models.CharField(default='Brak', max_length=60, verbose_name='Opis')),
                ('charge', models.CharField(max_length=20, verbose_name='Koszt')),
                ('photo', models.URLField(default='http://demo.sc.chinaz.com/Files/pic/icons/1499/chinaz3.png', verbose_name='Zdjęcie')),
                ('checked', models.BooleanField(default=False, verbose_name='Wypożyczony')),
            ],
            options={
                'verbose_name': 'Samochód',
                'verbose_name_plural': 'Samochody',
            },
        ),
    ]
