# Generated by Django 2.0.2 on 2018-05-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='fuel',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('Benzyna', 'Benzyna'), ('Benzyna + LPG', 'Benzyna + LPG')], max_length=20, verbose_name='Paliwo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gearbox',
            field=models.CharField(choices=[('Manualna', 'Manualna'), ('Automatyczna', 'Automatyczna'), ('Pół Automatyczna', 'Pół Automatyczna')], max_length=20, verbose_name='Skrzynia biegów'),
        ),
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Kombi', 'Kombi'), ('Sportowe | Coupe', 'Sportowe | Coupe'), ('Kabriolet', 'Kabriolet'), ('Limuzyna', 'Limuzyna'), ('Pickup', 'Pickup'), ('Terenowe', 'Terenowe'), ('Van | Minibus', 'Van | Minibus')], max_length=20, verbose_name='Typ'),
        ),
    ]
