# Generated by Django 2.0.5 on 2018-05-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20180515_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='number_plate',
            field=models.CharField(default='BS -----', max_length=20, verbose_name='Rejestracja'),
        ),
    ]
