# Generated by Django 2.0.5 on 2018-05-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_car_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.URLField(verbose_name='Zdjęcie'),
        ),
    ]
