# Generated by Django 2.0.5 on 2018-05-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20180524_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.URLField(default='https://www.freeiconspng.com/uploads/sport-car-icon-0.png', verbose_name='Zdjęcie'),
        ),
    ]
