# Generated by Django 2.0.5 on 2018-05-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0005_auto_20180518_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='raport',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
