# Generated by Django 2.0.5 on 2018-05-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0007_auto_20180521_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='worker',
            field=models.CharField(default='W trakcie rozpatrzania', max_length=20, verbose_name='Pracownik'),
        ),
    ]
