# Generated by Django 2.0.5 on 2018-05-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0009_auto_20180521_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='status',
            field=models.CharField(default='W trakcie rozpatrywania', max_length=20, verbose_name='Status'),
        ),
    ]
