# Generated by Django 2.0.5 on 2018-05-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0010_auto_20180521_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='raport',
            name='worker_reject',
            field=models.CharField(default='', max_length=20, verbose_name='Pracownik odbierający'),
        ),
        migrations.AlterField(
            model_name='raport',
            name='worker',
            field=models.CharField(default='', max_length=20, verbose_name='Pracownik wydający'),
        ),
        migrations.AlterField(
            model_name='raport',
            name='worker_accept',
            field=models.CharField(default='', max_length=20, verbose_name='Pracownik przyjmujący'),
        ),
    ]
