# Generated by Django 2.0.5 on 2018-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0011_auto_20180521_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='raport',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Aktywny'),
        ),
    ]
