# Generated by Django 2.0.5 on 2018-05-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0012_raport_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='raport',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='usuniety'),
        ),
    ]
