# Generated by Django 2.0.5 on 2018-05-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lease', '0013_raport_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raport',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='raport',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Usuniety'),
        ),
        migrations.AlterField(
            model_name='raport',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
